version: '3.8'
services:
  app-backstore:
    container_name: medusa_app_backstore
    build:
      context: ./my-store
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 9000:9000
      - 7000:7000
      - 7001:7001
    depends_on:
      - db
      - meilisearch
    networks:
      - my-store-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  app-frontstore:
    container_name: medusa_app_frontstore
    build:
      context: ./my-store-storefront
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - app-backstore
    networks:
      - my-store-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    hostname: db
    container_name: medusa_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: medusauser
      POSTGRES_PASSWORD: medusa_for_itds362
      POSTGRES_DB: medusadb
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/dump_store.sql:/tmp/dump_store.sql
    ports:
      - 5432:5432
    networks:
      - my-store-network
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: mallikas_for_itds362
    volumes:
      - meilisearch_data:/data.ms
    ports:
      - 7700:7700
    networks:
      - my-store-network
  redis:
    image: redis:latest
    container_name: medusa_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-store-network
volumes:
  meilisearch_data:
networks:
  my-store-network:
    driver: bridge