version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: medusauser
      POSTGRES_PASSWORD: medusa_for_itds362
      POSTGRES_DB: medusa
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pg_data: