version: '3.8'
services:
  app-backstore:
    container_name: medusa_app_backstore
    build:
      context: ./my-store
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - db
      - meilisearch
    networks:
      - my-store-network
  app-frontstore:
    container_name: medusa_app_frontstore
    build:
      context: ./my-store-storefront
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - app-backstore
    networks:
      - my-store-network
  db:
    hostname: db
    container_name: medusa_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: medusauser
      POSTGRES_PASSWORD: medusa_for_itds362
      POSTGRES_DB: medusadb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-store-network
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: mallikas_for_itds362
    volumes:
      - meilisearch_data:/data.ms
    ports:
      - 7700:7700
    networks:
      - my-store-network
volumes:
  pg_data:
  meilisearch_data:
networks:
  my-store-network:
    driver: bridge